import { Level } from './curriculum-data';

// Level 2 Unit Math (L2UM) - Intermediate Math Skills
export const L2UM: Level = {
  id: 'L2UM',
  number: 2,
  title: 'Level 2 Math',
  subject: 'math',
  description: 'Level 2 builds on foundational skills with place value understanding, two-digit operations with regrouping, money math, telling time, and data interpretation. Students will develop problem-solving skills through word problems and logical reasoning.',
  
  learningObjectives: [
    'Understand place value in two-digit numbers',
    'Add and subtract numbers up to 100 with regrouping',
    'Count and calculate with money',
    'Tell time to the hour and half hour',
    'Read and interpret graphs and data',
    'Solve multi-step word problems',
  ],
  
  assessmentMethods: [
    'Interactive digital exercises',
    'Visual place value models',
    'Money counting simulations',
    'Clock reading activities',
    'Graph interpretation tasks',
    'Word problem scenarios',
  ],
  
  rewardFeatures: [
    '16 achievement badges',
    '100 Robux per badge earned',
    'Rewards redeemable at 800 Robux (8 badges)',
    'Virtual certificates',
    'Unlockable avatar items',
    'Level graduation ceremony',
  ],
  
  totalRobux: 1600,
  redemptionThreshold: 800,
  
  lessons: [
    {
      id: 'L2UM-01',
      number: 1,
      title: 'I Can Understand Place Value',
      description: 'Learn to understand place value in two-digit numbers',
      skills: [
        { skill: 'Understanding tens and ones' },
        { skill: 'Expanded form notation' },
        { skill: 'Comparing place values' },
        { skill: 'Building numbers with base-10 blocks' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Great job understanding place value!' },
        { type: 'success', message: 'You correctly identified the tens and ones!' },
        { type: 'hint', message: 'Remember, the first digit shows the tens place.' },
        { type: 'retry', message: 'Try counting the tens blocks and ones blocks separately.' },
      ],
      badge: {
        id: 'badge-place-value',
        name: 'Place Value Pro',
        description: 'Master of place value',
        icon: 'Grid3x3',
        colorClass: 'bg-blue-100 text-blue-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L1UM-15'], // Requires L1 completion
    },
    {
      id: 'L2UM-02',
      number: 2,
      title: 'I Can Identify Numbers to 100',
      description: 'Identify and read numbers to 100',
      skills: [
        { skill: 'Number recognition (1-100)' },
        { skill: 'Reading two-digit numbers' },
        { skill: 'Ordering numbers' },
        { skill: 'Number patterns' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent number recognition!' },
        { type: 'encouragement', message: "You're becoming a number expert!" },
        { type: 'hint', message: 'Look at the tens place first, then the ones.' },
        { type: 'retry', message: 'Try using the hundreds chart to help you.' },
      ],
      badge: {
        id: 'badge-number-explorer',
        name: 'Number Explorer',
        description: 'Expert at identifying numbers to 100',
        icon: 'Search',
        colorClass: 'bg-purple-100 text-purple-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L2UM-01'],
    },
    {
      id: 'L2UM-03',
      number: 3,
      title: 'I Can Add Numbers up to 100',
      description: 'Add two-digit numbers',
      skills: [
        { skill: 'Two-digit addition' },
        { skill: 'Adding tens and ones' },
        { skill: 'Vertical addition format' },
        { skill: 'Estimation strategies' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Amazing addition skills!' },
        { type: 'success', message: 'You mastered adding larger numbers!' },
        { type: 'hint', message: 'Start by adding the ones place first.' },
        { type: 'hint', message: 'Remember to line up the digits correctly.' },
      ],
      badge: {
        id: 'badge-addition-ace',
        name: 'Addition Ace',
        description: 'Master of two-digit addition',
        icon: 'PlusCircle',
        colorClass: 'bg-green-100 text-green-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-02'],
    },
    {
      id: 'L2UM-04',
      number: 4,
      title: 'I Can Subtract Numbers up to 100',
      description: 'Subtract two-digit numbers',
      skills: [
        { skill: 'Two-digit subtraction' },
        { skill: 'Subtracting tens and ones' },
        { skill: 'Vertical subtraction format' },
        { skill: 'Checking answers with addition' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Wonderful subtraction work!' },
        { type: 'encouragement', message: "You're getting great at larger subtractions!" },
        { type: 'hint', message: 'Start with the ones place first.' },
        { type: 'hint', message: 'Check your answer by adding back.' },
      ],
      badge: {
        id: 'badge-subtraction-star-l2',
        name: 'Subtraction Star',
        description: 'Expert at two-digit subtraction',
        icon: 'MinusCircle',
        colorClass: 'bg-red-100 text-red-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-03'],
    },
    {
      id: 'L2UM-05',
      number: 5,
      title: 'I Can Use Repeated Addition',
      description: 'Use repeated addition to solve problems',
      skills: [
        { skill: 'Understanding repeated addition' },
        { skill: 'Skip counting connection' },
        { skill: 'Introduction to multiplication' },
        { skill: 'Equal groups concept' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Great job with repeated addition!' },
        { type: 'success', message: 'You understand equal groups perfectly!' },
        { type: 'hint', message: 'Count how many groups, then add them up.' },
        { type: 'hint', message: 'Try skip counting to find the total.' },
      ],
      badge: {
        id: 'badge-repeated-addition',
        name: 'Repeated Addition Rockstar',
        description: 'Master of repeated addition',
        icon: 'Repeat',
        colorClass: 'bg-yellow-100 text-yellow-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L2UM-03'],
    },
    {
      id: 'L2UM-06',
      number: 6,
      title: 'I Can Find Number Bonds',
      description: 'Find and use number bonds',
      skills: [
        { skill: 'Understanding number bonds' },
        { skill: 'Part-whole relationships' },
        { skill: 'Fact families' },
        { skill: 'Mental math strategies' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent work with number bonds!' },
        { type: 'success', message: 'You found all the parts and wholes!' },
        { type: 'hint', message: 'Think about what two numbers make the total.' },
        { type: 'retry', message: 'Try breaking the number into smaller parts.' },
      ],
      badge: {
        id: 'badge-number-bonds',
        name: 'Number Bond Builder',
        description: 'Expert at number bonds',
        icon: 'Link',
        colorClass: 'bg-indigo-100 text-indigo-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L2UM-04'],
    },
    {
      id: 'L2UM-07',
      number: 7,
      title: 'I Can Add with Regrouping',
      description: 'Add two-digit numbers with regrouping',
      skills: [
        { skill: 'Understanding regrouping concept' },
        { skill: 'Carrying to the tens place' },
        { skill: 'Adding with regrouping' },
        { skill: 'Checking work' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Amazing regrouping skills!' },
        { type: 'encouragement', message: "You're mastering challenging addition!" },
        { type: 'hint', message: 'When ones add to more than 10, regroup to tens.' },
        { type: 'hint', message: "Don't forget to add the regrouped ten!" },
      ],
      badge: {
        id: 'badge-regrouping-champion',
        name: 'Regrouping Champion',
        description: 'Master of addition with regrouping',
        icon: 'ArrowRightLeft',
        colorClass: 'bg-green-100 text-green-600',
        robuxValue: 100,
      },
      estimatedDuration: 45,
      prerequisites: ['L2UM-03', 'L2UM-06'],
    },
    {
      id: 'L2UM-08',
      number: 8,
      title: 'I Can Subtract with Regrouping',
      description: 'Subtract two-digit numbers with regrouping',
      skills: [
        { skill: 'Understanding borrowing' },
        { skill: 'Regrouping from tens to ones' },
        { skill: 'Subtracting with regrouping' },
        { skill: 'Verifying answers' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent regrouping subtraction!' },
        { type: 'success', message: 'You handled borrowing perfectly!' },
        { type: 'hint', message: 'Borrow 1 ten to make 10 ones.' },
        { type: 'hint', message: 'Remember to reduce the tens place by 1.' },
      ],
      badge: {
        id: 'badge-regrouping-subtraction',
        name: 'Regrouping Subtraction Star',
        description: 'Expert at subtraction with regrouping',
        icon: 'ArrowLeftRight',
        colorClass: 'bg-red-100 text-red-600',
        robuxValue: 100,
      },
      estimatedDuration: 45,
      prerequisites: ['L2UM-04', 'L2UM-06'],
    },
    {
      id: 'L2UM-09',
      number: 9,
      title: 'I Can Count and Add Money',
      description: 'Count coins, bills, and add money amounts',
      skills: [
        { skill: 'Counting mixed coins' },
        { skill: 'Dollar and cent notation' },
        { skill: 'Adding money amounts' },
        { skill: 'Making change' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Great money counting skills!' },
        { type: 'success', message: 'You calculated the total correctly!' },
        { type: 'hint', message: 'Count the largest coins first.' },
        { type: 'hint', message: 'Remember to line up the decimal points.' },
      ],
      badge: {
        id: 'badge-money-master-l2',
        name: 'Money Master',
        description: 'Expert at money math',
        icon: 'Coins',
        colorClass: 'bg-yellow-100 text-yellow-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-07', 'L2UM-08'],
    },
    {
      id: 'L2UM-10',
      number: 10,
      title: 'I Can Tell Time',
      description: 'Tell time to the hour and half hour',
      skills: [
        { skill: 'Reading analog clocks' },
        { skill: 'Hour hand and minute hand' },
        { skill: 'Time to the hour' },
        { skill: 'Time to the half hour' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Perfect time telling!' },
        { type: 'success', message: 'You read that clock correctly!' },
        { type: 'hint', message: 'The short hand shows the hour.' },
        { type: 'hint', message: 'When the long hand is on 6, it\'s half past.' },
      ],
      badge: {
        id: 'badge-time-teller',
        name: 'Time Teller',
        description: 'Master of telling time',
        icon: 'Clock',
        colorClass: 'bg-blue-100 text-blue-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-02'],
    },
    {
      id: 'L2UM-11',
      number: 11,
      title: 'I Can Read and Interpret Graphs',
      description: 'Read and interpret bar graphs and pictographs',
      skills: [
        { skill: 'Reading bar graphs' },
        { skill: 'Interpreting pictographs' },
        { skill: 'Comparing data' },
        { skill: 'Answering questions about data' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent graph reading!' },
        { type: 'success', message: 'You interpreted that data perfectly!' },
        { type: 'hint', message: 'Look at the labels and numbers carefully.' },
        { type: 'hint', message: 'Count the bars or pictures to compare.' },
      ],
      badge: {
        id: 'badge-data-detective',
        name: 'Data Detective',
        description: 'Expert at reading graphs',
        icon: 'BarChart2',
        colorClass: 'bg-purple-100 text-purple-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
    },
    {
      id: 'L2UM-12',
      number: 12,
      title: 'I Can Solve Word Problems',
      description: 'Solve addition and subtraction word problems',
      skills: [
        { skill: 'Understanding problem context' },
        { skill: 'Identifying key information' },
        { skill: 'Choosing the operation' },
        { skill: 'Solving and checking answers' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Wonderful problem solving!' },
        { type: 'success', message: 'You found the right answer!' },
        { type: 'hint', message: 'Read the problem carefully to find what you need.' },
        { type: 'hint', message: 'Think about whether you need to add or subtract.' },
      ],
      badge: {
        id: 'badge-word-problem-solver',
        name: 'Word Problem Solver',
        description: 'Master of word problems',
        icon: 'FileText',
        colorClass: 'bg-green-100 text-green-600',
        robuxValue: 100,
      },
      estimatedDuration: 45,
      prerequisites: ['L2UM-07', 'L2UM-08'],
    },
    {
      id: 'L2UM-13',
      number: 13,
      title: 'I Can Use Logic to Think About Numbers',
      description: 'Apply logical thinking to number problems',
      skills: [
        { skill: 'Pattern recognition' },
        { skill: 'Number sequences' },
        { skill: 'Logical reasoning' },
        { skill: 'Problem-solving strategies' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Great logical thinking!' },
        { type: 'success', message: 'You reasoned through that perfectly!' },
        { type: 'hint', message: 'Look for patterns in the numbers.' },
        { type: 'hint', message: 'Think about what makes sense.' },
      ],
      badge: {
        id: 'badge-logic-leader',
        name: 'Logic Leader',
        description: 'Expert at logical thinking',
        icon: 'Brain',
        colorClass: 'bg-indigo-100 text-indigo-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-06'],
    },
    {
      id: 'L2UM-14',
      number: 14,
      title: 'I Can Compare and Perform Operations',
      description: 'Compare numbers and perform operations',
      skills: [
        { skill: 'Comparing numbers using <, >, =' },
        { skill: 'Ordering numbers' },
        { skill: 'Choosing operations' },
        { skill: 'Multi-step problems' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Perfect comparison skills!' },
        { type: 'success', message: 'You chose the right operation!' },
        { type: 'hint', message: 'Think about which number is larger.' },
        { type: 'hint', message: 'Read what the problem is asking for.' },
      ],
      badge: {
        id: 'badge-operation-expert',
        name: 'Operation Expert',
        description: 'Master of number operations',
        icon: 'Calculator',
        colorClass: 'bg-blue-100 text-blue-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-12', 'L2UM-13'],
    },
    {
      id: 'L2UM-15',
      number: 15,
      title: 'I Can Reason with Numbers',
      description: 'Use reasoning to explain mathematical thinking',
      skills: [
        { skill: 'Explaining strategies' },
        { skill: 'Justifying answers' },
        { skill: 'Mathematical communication' },
        { skill: 'Multiple solution paths' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent mathematical reasoning!' },
        { type: 'success', message: 'You explained your thinking clearly!' },
        { type: 'hint', message: 'Try to explain why your answer makes sense.' },
        { type: 'hint', message: 'Think about different ways to solve it.' },
      ],
      badge: {
        id: 'badge-reasoning-ranger',
        name: 'Reasoning Ranger',
        description: 'Expert at mathematical reasoning',
        icon: 'MessageSquare',
        colorClass: 'bg-purple-100 text-purple-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L2UM-14'],
    },
    {
      id: 'L2UM-16',
      number: 16,
      title: 'I Can Complete Assessment and Graduate',
      description: 'Final comprehensive assessment for Level 2',
      skills: [
        { skill: 'Comprehensive review of all Level 2 skills' },
        { skill: 'Applied problem solving' },
        { skill: 'Multi-step reasoning' },
        { skill: 'Readiness for Level 3' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Congratulations on completing Level 2!' },
        { type: 'success', message: 'You mastered all Level 2 skills!' },
        { type: 'encouragement', message: "You're ready for Level 3 multiplication!" },
        { type: 'encouragement', message: 'Keep up the amazing work!' },
      ],
      badge: {
        id: 'badge-graduate-l2',
        name: 'Level 2 Graduate',
        description: 'Completed Level 2 Math',
        icon: 'GraduationCap',
        colorClass: 'bg-indigo-100 text-indigo-600',
        robuxValue: 100,
      },
      estimatedDuration: 60,
      prerequisites: ['L2UM-15', 'L2UM-09', 'L2UM-10', 'L2UM-11'],
    },
  ],
  
  redemptionOptions: [
    // Avatar Items
    {
      id: 'avatar-calculator-watch',
      category: 'avatar',
      name: 'Calculator Watch',
      description: 'High-tech watch with calculator',
      robuxCost: 800,
      icon: 'Watch',
    },
    {
      id: 'avatar-math-scientist-coat',
      category: 'avatar',
      name: 'Math Scientist Lab Coat',
      description: 'Professional lab coat for math scientists',
      robuxCost: 800,
      icon: 'Shirt',
    },
    {
      id: 'avatar-number-crown',
      category: 'avatar',
      name: 'Number Crown',
      description: 'Royal crown with number decorations',
      robuxCost: 800,
      icon: 'Crown',
    },
    {
      id: 'avatar-problem-solver-badge',
      category: 'avatar',
      name: 'Problem Solver Badge',
      description: 'Official problem solver badge',
      robuxCost: 800,
      icon: 'Shield',
    },
    
    // Game Passes
    {
      id: 'gamepass-time-traveler',
      category: 'gamepass',
      name: 'Time Traveler Mode',
      description: 'Travel through time solving math problems',
      robuxCost: 800,
      icon: 'Clock',
    },
    {
      id: 'gamepass-money-tycoon',
      category: 'gamepass',
      name: 'Money Tycoon Challenge',
      description: 'Build your money empire',
      robuxCost: 800,
      icon: 'Coins',
    },
    {
      id: 'gamepass-data-scientist',
      category: 'gamepass',
      name: 'Data Scientist Lab',
      description: 'Create and analyze graphs',
      robuxCost: 800,
      icon: 'BarChart2',
    },
    {
      id: 'gamepass-logic-puzzles',
      category: 'gamepass',
      name: 'Logic Puzzle Pack',
      description: 'Advanced logic challenges',
      robuxCost: 800,
      icon: 'Brain',
    },
    
    // Special Rewards
    {
      id: 'special-l2-certificate',
      category: 'special',
      name: 'Level 2 Certificate',
      description: 'Official Level 2 completion certificate',
      robuxCost: 0,
      icon: 'Award',
    },
    {
      id: 'special-l2-trophy',
      category: 'special',
      name: 'Level 2 Golden Trophy',
      description: 'Shiny golden trophy for achievements',
      robuxCost: 0,
      icon: 'Trophy',
    },
    {
      id: 'special-math-genius-badge',
      category: 'special',
      name: 'Math Genius Profile Badge',
      description: 'Show off your math genius status',
      robuxCost: 0,
      icon: 'Star',
    },
    {
      id: 'special-l3-early-access',
      category: 'special',
      name: 'Early Access to Level 3',
      description: 'Start Level 3 multiplication early',
      robuxCost: 0,
      icon: 'Rocket',
    },
  ],
};

export default L2UM;
