import { Level } from './curriculum-data';

// Level 3 Unit Math (L3UM) - Multiplication Mastery
export const L3UM: Level = {
  id: 'L3UM',
  number: 3,
  title: 'Level 3 Math',
  subject: 'math',
  description: 'Level 3 focuses on multiplication mastery and introduction to division. Students will learn all multiplication tables from 0-12 through arrays, mental math strategies, and problem-solving. This level builds the foundation for advanced mathematical operations.',
  
  learningObjectives: [
    'Understand place value in larger numbers',
    'Use mental math strategies for quick calculations',
    'Master multiplication tables 0-12',
    'Understand the relationship between multiplication and division',
    'Use arrays to visualize multiplication',
    'Solve multiplication and division problems',
  ],
  
  assessmentMethods: [
    'Timed multiplication drills',
    'Array building activities',
    'Mental math challenges',
    'Division problem solving',
    'Word problem applications',
    'Comprehensive multiplication assessment',
  ],
  
  rewardFeatures: [
    '16 achievement badges',
    '100 Robux per badge earned',
    'Rewards redeemable at 800 Robux (8 badges)',
    'Virtual certificates',
    'Unlockable avatar items',
    'Level graduation ceremony',
  ],
  
  totalRobux: 1600,
  redemptionThreshold: 800,
  
  lessons: [
    {
      id: 'L3UM-01',
      number: 1,
      title: 'I Can Understand Place Value in Larger Numbers',
      description: 'Understand place value in three-digit numbers',
      skills: [
        { skill: 'Hundreds, tens, and ones' },
        { skill: 'Expanded form for larger numbers' },
        { skill: 'Number comparisons' },
        { skill: 'Building larger numbers' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent place value understanding!' },
        { type: 'success', message: 'You identified all the place values correctly!' },
        { type: 'hint', message: 'Remember: hundreds, tens, then ones.' },
        { type: 'retry', message: 'Try breaking the number into its parts.' },
      ],
      badge: {
        id: 'badge-place-value-pro',
        name: 'Place Value Pro',
        description: 'Master of place value',
        icon: 'Grid3x3',
        colorClass: 'bg-blue-100 text-blue-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L2UM-16'], // Requires L2 completion
    },
    {
      id: 'L3UM-02',
      number: 2,
      title: 'I Can Use Mental Math Strategies',
      description: 'Use mental math for quick calculations',
      skills: [
        { skill: 'Breaking apart numbers' },
        { skill: 'Making tens strategy' },
        { skill: 'Doubling and halving' },
        { skill: 'Compensation method' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Amazing mental math skills!' },
        { type: 'encouragement', message: "You're calculating like a pro!" },
        { type: 'hint', message: 'Try breaking the numbers into easier parts.' },
        { type: 'hint', message: 'Look for numbers that make 10.' },
      ],
      badge: {
        id: 'badge-mental-math-master',
        name: 'Mental Math Master',
        description: 'Expert at mental calculations',
        icon: 'Zap',
        colorClass: 'bg-purple-100 text-purple-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L3UM-01'],
    },
    {
      id: 'L3UM-03',
      number: 3,
      title: 'I Can Use Arrays',
      description: 'Use arrays to represent multiplication',
      skills: [
        { skill: 'Understanding array structure' },
        { skill: 'Rows and columns' },
        { skill: 'Arrays as repeated addition' },
        { skill: 'Writing multiplication from arrays' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Perfect array understanding!' },
        { type: 'success', message: 'You visualized multiplication beautifully!' },
        { type: 'hint', message: 'Count the rows, then the items in each row.' },
        { type: 'hint', message: 'Arrays help you see multiplication.' },
      ],
      badge: {
        id: 'badge-array-architect',
        name: 'Array Architect',
        description: 'Master of arrays',
        icon: 'Grid2x2',
        colorClass: 'bg-green-100 text-green-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L3UM-02'],
    },
    {
      id: 'L3UM-04',
      number: 4,
      title: 'I Can Understand Basic Division',
      description: 'Learn the concept of division',
      skills: [
        { skill: 'Understanding division as sharing' },
        { skill: 'Division as repeated subtraction' },
        { skill: 'Equal groups in division' },
        { skill: 'Relationship to multiplication' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Great job understanding division!' },
        { type: 'success', message: 'You shared equally perfectly!' },
        { type: 'hint', message: 'Think about sharing into equal groups.' },
        { type: 'hint', message: 'Division is the opposite of multiplication.' },
      ],
      badge: {
        id: 'badge-division-discoverer',
        name: 'Division Discoverer',
        description: 'Discovered the power of division',
        icon: 'Divide',
        colorClass: 'bg-yellow-100 text-yellow-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L3UM-03'],
    },
    {
      id: 'L3UM-05',
      number: 5,
      title: 'I Can Multiply by 1 and 0',
      description: 'Master multiplication by 1 and 0',
      skills: [
        { skill: 'Identity property (×1)' },
        { skill: 'Zero property (×0)' },
        { skill: 'Understanding why 0×n = 0' },
        { skill: 'Understanding why 1×n = n' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Perfect understanding of 1 and 0!' },
        { type: 'success', message: 'You mastered these special rules!' },
        { type: 'hint', message: 'Any number times 1 stays the same.' },
        { type: 'hint', message: 'Any number times 0 equals 0.' },
      ],
      badge: {
        id: 'badge-one-zero-hero',
        name: 'One and Zero Hero',
        description: 'Master of 1 and 0 multiplication',
        icon: 'CircleDot',
        colorClass: 'bg-indigo-100 text-indigo-600',
        robuxValue: 100,
      },
      estimatedDuration: 30,
      prerequisites: ['L3UM-04'],
    },
    {
      id: 'L3UM-06',
      number: 6,
      title: 'I Can Multiply by 10 and 5',
      description: 'Master multiplication by 10 and 5',
      skills: [
        { skill: 'Multiplying by 10 (adding zero)' },
        { skill: 'Skip counting by 10s' },
        { skill: 'Multiplying by 5 patterns' },
        { skill: 'Skip counting by 5s' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent work with 10s and 5s!' },
        { type: 'success', message: 'You found the patterns!' },
        { type: 'hint', message: 'Multiplying by 10 just adds a zero.' },
        { type: 'hint', message: 'Five times tables end in 0 or 5.' },
      ],
      badge: {
        id: 'badge-ten-five-expert',
        name: 'Ten and Five Expert',
        description: 'Master of 10 and 5 times tables',
        icon: 'Hash',
        colorClass: 'bg-blue-100 text-blue-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L3UM-05'],
    },
    {
      id: 'L3UM-07',
      number: 7,
      title: 'I Can Multiply by 2',
      description: 'Master the 2 times table',
      skills: [
        { skill: 'Doubling numbers' },
        { skill: 'Even number patterns' },
        { skill: '2 times table facts' },
        { skill: 'Skip counting by 2s' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Great job with the 2 times table!' },
        { type: 'success', message: 'You doubled those numbers perfectly!' },
        { type: 'hint', message: 'Multiplying by 2 is the same as doubling.' },
        { type: 'hint', message: 'Use skip counting by 2s to help.' },
      ],
      badge: {
        id: 'badge-two-times-titan',
        name: 'Two Times Titan',
        description: 'Master of 2 times table',
        icon: 'Copy',
        colorClass: 'bg-purple-100 text-purple-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L3UM-06'],
    },
    {
      id: 'L3UM-08',
      number: 8,
      title: 'I Can Multiply by 3',
      description: 'Master the 3 times table',
      skills: [
        { skill: '3 times table facts' },
        { skill: 'Skip counting by 3s' },
        { skill: 'Building on 2s (add one more group)' },
        { skill: 'Three groups visualization' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Fantastic work with 3s!' },
        { type: 'success', message: 'You mastered the 3 times table!' },
        { type: 'hint', message: 'Think of three equal groups.' },
        { type: 'hint', message: 'Use skip counting: 3, 6, 9, 12...' },
      ],
      badge: {
        id: 'badge-three-times-champ',
        name: 'Three Times Champ',
        description: 'Champion of 3 times table',
        icon: 'Triangle',
        colorClass: 'bg-green-100 text-green-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L3UM-07'],
    },
    {
      id: 'L3UM-09',
      number: 9,
      title: 'I Can Multiply by 4',
      description: 'Master the 4 times table',
      skills: [
        { skill: '4 times table facts' },
        { skill: 'Double double strategy (2×2)' },
        { skill: 'Skip counting by 4s' },
        { skill: 'Four groups visualization' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Amazing work with 4s!' },
        { type: 'success', message: 'You conquered the 4 times table!' },
        { type: 'hint', message: 'Try doubling, then doubling again.' },
        { type: 'hint', message: 'Four times is like 2×2.' },
      ],
      badge: {
        id: 'badge-four-times-fighter',
        name: 'Four Times Fighter',
        description: 'Fighter of 4 times table',
        icon: 'Square',
        colorClass: 'bg-red-100 text-red-600',
        robuxValue: 100,
      },
      estimatedDuration: 35,
      prerequisites: ['L3UM-08'],
    },
    {
      id: 'L3UM-10',
      number: 10,
      title: 'I Can Multiply by 6',
      description: 'Master the 6 times table',
      skills: [
        { skill: '6 times table facts' },
        { skill: 'Building on 5s (add one more)' },
        { skill: 'Skip counting by 6s' },
        { skill: 'Six groups visualization' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Superb work with 6s!' },
        { type: 'success', message: 'You mastered the 6 times table!' },
        { type: 'hint', message: 'Think 5 groups plus 1 more group.' },
        { type: 'hint', message: 'Double the 3s to get 6s.' },
      ],
      badge: {
        id: 'badge-six-times-superstar',
        name: 'Six Times Superstar',
        description: 'Superstar of 6 times table',
        icon: 'Hexagon',
        colorClass: 'bg-yellow-100 text-yellow-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L3UM-09'],
    },
    {
      id: 'L3UM-11',
      number: 11,
      title: 'I Can Multiply by 7',
      description: 'Master the 7 times table',
      skills: [
        { skill: '7 times table facts' },
        { skill: 'Skip counting by 7s' },
        { skill: 'Using patterns and strategies' },
        { skill: 'Seven groups visualization' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Excellent work with 7s!' },
        { type: 'success', message: 'You tackled the tricky 7 times table!' },
        { type: 'hint', message: 'Look for patterns in the numbers.' },
        { type: 'hint', message: 'Practice makes perfect with 7s!' },
      ],
      badge: {
        id: 'badge-seven-times-specialist',
        name: 'Seven Times Specialist',
        description: 'Specialist of 7 times table',
        icon: 'Star',
        colorClass: 'bg-indigo-100 text-indigo-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L3UM-10'],
    },
    {
      id: 'L3UM-12',
      number: 12,
      title: 'I Can Multiply by 8',
      description: 'Master the 8 times table',
      skills: [
        { skill: '8 times table facts' },
        { skill: 'Double 4s strategy' },
        { skill: 'Skip counting by 8s' },
        { skill: 'Eight groups visualization' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Outstanding work with 8s!' },
        { type: 'success', message: 'You mastered the 8 times table!' },
        { type: 'hint', message: 'Double the 4s to get 8s.' },
        { type: 'hint', message: 'Eight times ends in even numbers.' },
      ],
      badge: {
        id: 'badge-eight-times-expert',
        name: 'Eight Times Expert',
        description: 'Expert of 8 times table',
        icon: 'Octagon',
        colorClass: 'bg-blue-100 text-blue-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L3UM-11'],
    },
    {
      id: 'L3UM-13',
      number: 13,
      title: 'I Can Multiply by 9',
      description: 'Master the 9 times table',
      skills: [
        { skill: '9 times table facts' },
        { skill: 'Finger trick for 9s' },
        { skill: 'Pattern: digits add to 9' },
        { skill: 'Ten minus one strategy' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Incredible work with 9s!' },
        { type: 'success', message: 'You found the amazing 9s patterns!' },
        { type: 'hint', message: 'Try 10 times, then subtract one group.' },
        { type: 'hint', message: 'Look at the pattern: 9, 18, 27, 36...' },
      ],
      badge: {
        id: 'badge-nine-times-ninja',
        name: 'Nine Times Ninja',
        description: 'Ninja master of 9 times table',
        icon: 'Sparkles',
        colorClass: 'bg-purple-100 text-purple-600',
        robuxValue: 100,
      },
      estimatedDuration: 40,
      prerequisites: ['L3UM-12'],
    },
    {
      id: 'L3UM-14',
      number: 14,
      title: 'I Can Multiply by 11 and 12',
      description: 'Master the 11 and 12 times tables',
      skills: [
        { skill: '11 times table pattern' },
        { skill: '12 times table facts' },
        { skill: 'Doubling 6s for 12s' },
        { skill: 'Advanced multiplication strategies' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Phenomenal work with 11 and 12!' },
        { type: 'success', message: 'You completed all the times tables!' },
        { type: 'hint', message: 'For 11s: repeat the digit (3×11=33).' },
        { type: 'hint', message: 'For 12s: double the 6s.' },
      ],
      badge: {
        id: 'badge-eleven-twelve-whiz',
        name: 'Eleven Twelve Whiz',
        description: 'Whiz at 11 and 12 times tables',
        icon: 'Award',
        colorClass: 'bg-green-100 text-green-600',
        robuxValue: 100,
      },
      estimatedDuration: 45,
      prerequisites: ['L3UM-13'],
    },
    {
      id: 'L3UM-15',
      number: 15,
      title: 'I Can Solve Multiplication and Division',
      description: 'Apply multiplication and division to problems',
      skills: [
        { skill: 'Choosing the operation' },
        { skill: 'Word problem solving' },
        { skill: 'Fact families' },
        { skill: 'Multi-step problems' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Brilliant problem solving!' },
        { type: 'success', message: 'You applied your multiplication skills perfectly!' },
        { type: 'hint', message: 'Read carefully to choose multiply or divide.' },
        { type: 'hint', message: 'Use what you know about fact families.' },
      ],
      badge: {
        id: 'badge-mult-div-dynamo',
        name: 'Multiplication Division Dynamo',
        description: 'Dynamo at multiplication and division',
        icon: 'Zap',
        colorClass: 'bg-red-100 text-red-600',
        robuxValue: 100,
      },
      estimatedDuration: 45,
      prerequisites: ['L3UM-14'],
    },
    {
      id: 'L3UM-16',
      number: 16,
      title: 'I Can Complete Assessment and Graduate',
      description: 'Final comprehensive assessment for Level 3',
      skills: [
        { skill: 'All multiplication tables 0-12' },
        { skill: 'Division understanding' },
        { skill: 'Problem-solving application' },
        { skill: 'Readiness for Level 4' },
      ],
      feedbackPrompts: [
        { type: 'success', message: 'Congratulations on completing Level 3!' },
        { type: 'success', message: 'You mastered multiplication!' },
        { type: 'encouragement', message: "You're ready for advanced math!" },
        { type: 'encouragement', message: 'Your hard work paid off!' },
      ],
      badge: {
        id: 'badge-graduate-l3',
        name: 'Level 3 Graduate',
        description: 'Completed Level 3 Math - Multiplication Master',
        icon: 'GraduationCap',
        colorClass: 'bg-indigo-100 text-indigo-600',
        robuxValue: 100,
      },
      estimatedDuration: 60,
      prerequisites: ['L3UM-15'],
    },
  ],
  
  redemptionOptions: [
    // Avatar Items
    {
      id: 'avatar-multiplication-cape',
      category: 'avatar',
      name: 'Multiplication Master Cape',
      description: 'Flowing cape with times table patterns',
      robuxCost: 800,
      icon: 'Shirt',
    },
    {
      id: 'avatar-calculator-glasses',
      category: 'avatar',
      name: 'Smart Calculator Glasses',
      description: 'High-tech glasses for math geniuses',
      robuxCost: 800,
      icon: 'Glasses',
    },
    {
      id: 'avatar-times-table-shirt',
      category: 'avatar',
      name: 'Times Table Champion Shirt',
      description: 'Exclusive shirt with all times tables',
      robuxCost: 800,
      icon: 'Shirt',
    },
    {
      id: 'avatar-multiplication-crown',
      category: 'avatar',
      name: 'Multiplication King Crown',
      description: 'Golden crown for multiplication royalty',
      robuxCost: 800,
      icon: 'Crown',
    },
    
    // Game Passes
    {
      id: 'gamepass-speed-multiplication',
      category: 'gamepass',
      name: 'Speed Multiplication Arena',
      description: 'Compete in timed multiplication battles',
      robuxCost: 800,
      icon: 'Zap',
    },
    {
      id: 'gamepass-division-quest',
      category: 'gamepass',
      name: 'Division Quest Adventure',
      description: 'Epic division problem quests',
      robuxCost: 800,
      icon: 'Sword',
    },
    {
      id: 'gamepass-array-builder',
      category: 'gamepass',
      name: 'Array Builder Studio',
      description: 'Create and solve array challenges',
      robuxCost: 800,
      icon: 'Grid2x2',
    },
    {
      id: 'gamepass-times-table-tournament',
      category: 'gamepass',
      name: 'Times Table Tournament',
      description: 'Compete in multiplication tournaments',
      robuxCost: 800,
      icon: 'Trophy',
    },
    
    // Special Rewards
    {
      id: 'special-l3-certificate',
      category: 'special',
      name: 'Multiplication Master Certificate',
      description: 'Official multiplication mastery certificate',
      robuxCost: 0,
      icon: 'Award',
    },
    {
      id: 'special-l3-trophy',
      category: 'special',
      name: 'Platinum Multiplication Trophy',
      description: 'Platinum trophy for multiplication excellence',
      robuxCost: 0,
      icon: 'Trophy',
    },
    {
      id: 'special-math-wizard-badge',
      category: 'special',
      name: 'Math Wizard Profile Badge',
      description: 'Legendary math wizard status',
      robuxCost: 0,
      icon: 'Sparkles',
    },
    {
      id: 'special-l4-early-access',
      category: 'special',
      name: 'Early Access to Level 4',
      description: 'Be first to try Level 4 content',
      robuxCost: 0,
      icon: 'Rocket',
    },
  ],
};

export default L3UM;
